In [120]:
import numpy as np
import torch.nn as nn
from numpy.linalg import norm 

In [111]:
a = np.array([(2,3,4,5),(3,4,8,9),(5,1,9,2)])
print(a)
a = a.reshape(12,)
print(a.shape)

[[2 3 4 5]
 [3 4 8 9]
 [5 1 9 2]]
(12,)


In [112]:
b = np.array([(2,3,4,5),(3,4,8,9),(5,1,9,2)])
b = b.T

b = b.reshape(12,)
print(b.shape)

(12,)


In [104]:
print(b)

[[2 3 5]
 [3 4 1]
 [4 8 9]
 [5 9 2]]


In [95]:
#  b = b.reshape(4,9)

In [113]:
c = np.dot(a,b)
print(c)

303


In [105]:
# b = b.reshape(3,4)

In [115]:
 e = np.linalg.norm(a)

f = np.linalg.norm(b)

In [116]:
print(e)
print(f)

18.303005217723125
18.303005217723125


In [117]:
product = e*f
print(product)

334.99999999999994


In [134]:
#cosine similarity
res = c/product
print(res)

#Cosine similarity
x1 = np.dot(a,b) / (norm(a) * norm(b))

print(x1)

0.9044776119402986
0.9044776


In [135]:
#cosine distance
x2 = 1 -  (np.dot(a,b) / (norm(a) * norm(b)))
print(x2)

0.09552240371704102


In [136]:
a = torch.Tensor(a)
b = torch.Tensor(b)

cos = nn.CosineSimilarity(dim=0, eps=1e-6)
output = cos(a, b)

In [137]:
print(output)
output = output.numpy()
print(output)

tensor(0.9045)
0.9044776


In [138]:
dist = 1 - output
print(dist)

0.09552240371704102


In [128]:
dist = dist.numpy()
print(dist)

0.0955224


In [60]:
x = (2*3*4*5)/4

In [62]:
print(x)

30.0


In [77]:
#norm

a = [1,2,3,1,1]

print(norm(a))

Z = 1+4+9+1+1
Z = np.sqrt(Z)
print(Z)

4.0
4.0


In [75]:
s = np
# print(s)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [204]:
#addition

a = np.random.rand(5)
print(a)
print(a.shape)
b = np.random.uniform(2,10,5)
print(b)
print(b.shape)

[0.76067138 0.72732265 0.36284783 0.92103136 0.97974268]
(5,)
[7.94716108 7.1214885  6.34936248 7.21077155 6.55505281]
(5,)


In [205]:
c = a+b
print(c)

[8.70783245 7.84881114 6.71221031 8.1318029  7.53479548]


In [206]:
d = 0.0738779 + 4.17418495

In [207]:
print(d)

4.24806285


In [208]:
# d = np.cross(a,b)
# print(d)

In [215]:
ab = np.random.randint(2,10,(4))

In [210]:
x = list(ab)

In [211]:
print(x)

[9, 3, 8, 5]


In [212]:
y = tuple(x)

In [216]:
print(y)
ab = 

(9, 3, 8, 5)


AttributeError: 'numpy.ndarray' object has no attribute 'int'

In [214]:
ab = torch.IntTensor(ab)

In [203]:
print(ab)

tensor([8, 2, 4, 6], dtype=torch.int32)
