In [ ]:
#Matrix - Basics

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Creating a Matrix using numpy

matrix = np.array([(2,3),(4,5)])
print(matrix)

[[2 3]
 [4 5]]


In [5]:
matrix.shape

(2, 2)

In [ ]:
#Creating Matrix with Random Values

In [7]:
random_matrix = np.random.rand(3,3)

In [8]:
print(random_matrix)

[[0.01228569 0.35655654 0.74516517]
 [0.04580967 0.0032696  0.81989908]
 [0.38539406 0.29525703 0.59644788]]


In [13]:
random = np.random.randint(3,10,[2,3])

In [14]:
print(random)

[[6 7 6]
 [9 6 9]]


In [23]:
#Matrix with all the values as 1

matrix = np.ones((2,3),dtype = float)

In [24]:
print(matrix)

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
#Null Matrix/Zero Matrix

null_matrix = np.zeros((4,4))

In [28]:
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
#Identity Matrix

eye_matrix = np.eye(4,3)

In [30]:
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [31]:
#Transpose of a Matrix

In [33]:
z = np.array([(2,3,4),(5,6,7)])
x = np.transpose(z)
print(x)

[[2 5]
 [3 6]
 [4 7]]


In [34]:
#Addition of Matrices

In [35]:
a= np.array([(3,4,5),(1,6,2)])

In [36]:
print(a)

[[3 4 5]
 [1 6 2]]


In [38]:
b= np.array([(12,3,1),(9,5,8)])

In [39]:
print(b)

[[12  3  1]
 [ 9  5  8]]


In [40]:
res = a+b
print(res)

[[24  6  2]
 [18 10 16]]


In [42]:
a= np.array([(3,4,5),(1,6,2)])
b= np.array([(12,3,1),(9,5,8)])
sub_res = a-b
print(sub_res)

[[-9  1  4]
 [-8  1 -6]]


In [43]:
a= np.array([(3,4,5),(1,6,2)])
b= np.array([(12,3,1),(9,5,8)])
x = np.subtract(a,b)

In [44]:
print(x)

[[-9  1  4]
 [-8  1 -6]]


In [45]:
#Multiplying a matrix by a scaler

In [46]:
x=5
y =np.array([(4,6,3),(1,2,3)])
z = x*y
print(z)

[[20 30 15]
 [ 5 10 15]]


In [47]:
res = np.multiply(x,y)

In [48]:
print(res)

[[20 30 15]
 [ 5 10 15]]


In [49]:
#Multiplying the 2 Matrices

In [70]:
a = np.random.randint(20,size=(4,3))

In [71]:
b = np.random.randint(50,size = (3,5))


In [72]:

print(a,b)

[[11 14  0]
 [ 9 14 15]
 [16 10 17]
 [ 5 10 10]] [[29 39 35 29 12]
 [31 46 20 18 17]
 [45  6 14  5 28]]


In [73]:
z = np.dot(a,b)

In [74]:
print(z)

[[ 753 1073  665  571  370]
 [1370 1085  805  588  766]
 [1539 1186  998  729  838]
 [ 905  715  515  375  510]]


In [75]:
#Elements wise Matrix Multiplication

In [77]:
a = np.random.randint(20,size=(3,3))
b = np.random.randint(50,size = (3,3))
product = np.multiply(a,b)

In [78]:
print(product)

[[ 81  91 196]
 [630 736  42]
 [210 444   0]]
