In [7]:
import numpy as np
import random
list = np.array([1,2,3,4,5])
print(list)
type(list)

[1 2 3 4 5]


numpy.ndarray

In [8]:
list.shape

(5,)

In [9]:
arr = np.array([(1,2,4),(4,5,6)])
print(arr)
type(arr)
arr.shape

[[1 2 4]
 [4 5 6]]


(2, 3)

In [17]:
x = np.full((4,5),5)
print(x)


[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [23]:
#identity matrice
a = np.eye((5))
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
#matrix of ones
z = np.ones((3,3))
print(z)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
#random values of numpy array
rand = np.random.random((3,5))
print(rand)

[[0.16180397 0.36913471 0.7190734  0.03421016 0.22860614]
 [0.95820104 0.28603954 0.09199889 0.57912752 0.97416001]
 [0.03801573 0.65326473 0.87875871 0.24942941 0.02425516]]


In [31]:
#generate random array between any range
x= np.random.randint(10,100,(2,4))
print(x)

[[73 16 93 75]
 [61 97 87 21]]


In [37]:
#array od evenly spaced values
d = np.linspace(10,50,41)
print(d)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49. 50.]


In [39]:
a = np.arange(10,30,4)
print(a)


[10 14 18 22 26]


In [48]:
#convert a list to numpy array
list = [10,20,30,40]
type(list)
np_array = np.asarray(list)
print(np_array)
type(np_array)

[10 20 30 40]


numpy.ndarray

In [49]:
#analysis

array = np.random.randint(10,100,(2,4))
print(array)


[[49 34 17 39]
 [37 15 82 82]]


In [50]:
print(array.shape)

(2, 4)


In [51]:
print(array.ndim)

2


In [52]:
print(array.size)

8


In [53]:
print(array.dtype)

int32


In [54]:
#Mathematical Operations

list1 = [2,4,6,8]
list2 = [5,6,7,8,9]

print(list1+list2) 


[2, 4, 6, 8, 5, 6, 7, 8, 9]


In [55]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 3 8]
 [0 3 4]
 [0 2 9]]
[[16 12 15]
 [19 14 19]
 [15 17 13]]


In [56]:
print(a+b)

[[19 15 23]
 [19 17 23]
 [15 19 22]]


In [61]:
 c = print(np.add(a,b))

[[19 15 23]
 [19 17 23]
 [15 19 22]]


In [67]:
array = np.random.randint(10,20,(3,4))
print(array)
print(array.shape)

[[19 12 12 14]
 [17 16 11 17]
 [13 17 11 17]]
(3, 4)


In [68]:
#transpose

trans = np.transpose(array)
print(trans)
print(trans.shape)


[[19 17 13]
 [12 16 17]
 [12 11 11]
 [14 17 17]]
(4, 3)


In [69]:
trans2 = array.T
print(trans2)

[[19 17 13]
 [12 16 17]
 [12 11 11]
 [14 17 17]]
